### ISSUE TITLE
Research implementing ToolTips (image hover)

### ISSUE THREAD

**Issue by Cloud9-Sec** [cs481-ekh/s22-hospsim#35]
Research how to implement tooltips by hovering of a "?" icon within our existing codebase.

**Comment by AndrewGerberBSU** [comment]
After googling packages we could use I landed on this:
https://paladini.dev/posts/how-to-make-an-extremely-reusable-tooltip-component-with-react--and-nothing-else/

it gave me a .js and .css for using a tooltip. I implemented these files. I then when to NounProject and decided on a logo to append to these tooltips for some aspects. The Tooltip is built in a way where it is a wrapper and you can contain all the elements you want to have the tooltip. This allowed me to add a tooltip to the icon I found.
