### ISSUE TITLE
Research React.js calendar code

### ISSUE THREAD

**Issue by Cloud9-Sec** [cs481-ekh/s22-hospsim#37]
Research how to implement react.js calendar code. No CSS needed at this stage, merely just researching the code.

**Comment by snakeround** [comment]
There are a lot of choices but some do not offer the customization options we will need, some also do not appear as stable as these 2:

* Fullcalendar.io https://fullcalendar.io/docs/react
* Big Calendar https://jquense.github.io/react-big-calendar/examples/index.html
