### ISSUE TITLE
Evening shifts only showing up in 1 hour block

### ISSUE THREAD

**Issue by Cloud9-Sec** [cs481-ekh/s22-hospsim#99]
Evening shift (8 hour evening) only showing up as one hour blocks on the calendar.

**Comment by AndrewGerberBSU** [comment]
i take this as a personal slight

**Comment by AndrewGerberBSU** [comment]
<img width="544" alt="Screen Shot 2022-04-05 at 12 42 33 PM" src="https://user-images.githubusercontent.com/66980113/161827085-1456a645-f3ee-4658-94d4-4139293735f1.png">

**Comment by Cloud9-Sec** [comment]
Easy there big fella, try putting the end date sometime in the next day. You may need to try the 12 hour shift if you haven't pulled from main from my last PR
